// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_PAC325.Data;

#nullable disable

namespace Proyecto_PAC325.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_PAC325.Models.BitacoraModel", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("longtext");

                    b.Property<string>("DatosPosteriores")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionDeEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaDeEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<string>("TablaDeEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDeEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEvento");

                    b.ToTable("BitacoraEventos");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.CajaModel", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoSINPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCaja");

                    b.ToTable("CAJAS");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.ComercioModel", b =>
                {
                    b.Property<int>("IdComercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoDeComercio")
                        .HasColumnType("int");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("IdComercio");

                    b.ToTable("COMERCIOS");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.ConfigComercioModel", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Comision")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<int>("TipoConfiguracion")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("IdComercio");

                    b.ToTable("CONFIGURACIONES_COMERCIOS");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.ReporteMensualModel", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadDeCajas")
                        .HasColumnType("int");

                    b.Property<int>("CantidadDeSINPES")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDelReporte")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotalComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalRecaudado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdReporte");

                    b.ToTable("REPORTES_MENSUALES");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.SinpeModel", b =>
                {
                    b.Property<int>("IdSinpe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreDestinatario")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreOrigen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TelefonoDestinatario")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TelefonoOrigen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdSinpe");

                    b.ToTable("SINPE");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdNetUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdComercio");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.ConfigComercioModel", b =>
                {
                    b.HasOne("Proyecto_PAC325.Models.ComercioModel", "Comercio")
                        .WithMany()
                        .HasForeignKey("IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("Proyecto_PAC325.Models.UsuarioModel", b =>
                {
                    b.HasOne("Proyecto_PAC325.Models.ComercioModel", "Comercio")
                        .WithMany()
                        .HasForeignKey("IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });
#pragma warning restore 612, 618
        }
    }
}
